# Generated by Django 4.2 on 2023-05-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
