# Generated by Django 4.2 on 2023-05-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='value',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, default='defaultUser.jpg', null=True, upload_to=''),
        ),
    ]
