# Generated by Django 4.2 on 2023-05-03 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_value_messages_text_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='changed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='dateChanged',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='textChanged',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 10, 45, 25, 485628), null=True),
        ),
    ]
