# Generated by Django 4.2 on 2023-05-03 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_messages_changed_messages_datechanged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='dateChanged',
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 12, 34, 0, 58080), null=True),
        ),
    ]
