# Generated by Django 4.2 on 2023-05-03 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_messages_datechanged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='dateChanged',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 12, 34, 57, 686634), null=True),
        ),
    ]
