# Generated by Django 4.2 on 2023-05-03 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_messages_datechanged_alter_messages_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='dateChanged',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 3, 12, 53, 0, 694426), null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 12, 53, 0, 694426), null=True),
        ),
    ]
