# Generated by Django 4.2 on 2023-05-03 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_messages_datechanged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='dateChanged',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 3, 13, 47, 5, 592697), null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 13, 47, 5, 592697), null=True),
        ),
    ]
